[workspace]
members = [
  # "src/bootstrap",
  "compiler/qhantoom",
  "compiler/qhantoom-driver",
]

[workspace.package]
version = "0.0.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
