[package]
name = "qhantoom-ui"
version = "0.1.0"
authors = ["monsieurbadia <iam@monsieurbadia.com>"]
edition = "2018"

description = """
the qhantoom ui compiler
"""

[lib]
name = "qhantoom_ui"
path = "src/lib.rs"
doctest = false

[dev-dependencies]
criterion = "0.3.4"
