[package]
name = "qhantoom"
version = "0.1.0"
authors = ["monsieurbadia <iam@monsieurbadia.com>"]
edition = "2018"

description = """
the qhantoom compiler
"""

[lib]
name = "qhantoom"
path = "src/lib.rs"
doctest = false

[dev-dependencies]
criterion = "0.3.4"
