[package]
name = "qhantoom"
version = "0.0.0"
description = "the qhantoom compiler"
authors = ["monsieurbadia <iam@monsieurbadia.com>"]
edition = "2018"

[lib]
name = "qhantoom"
path = "src/lib.rs"
doctest = false

[dependencies]
mwa = { git = "https://github.com/monsieurbadia/mwa" }

[dev-dependencies]
criterion = "0.3.4"
